.base: &base
  forwardAgent: false
  multiplexing: true
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  roles:
    - app
    - db
  deploy_path: ~/bot

10.0.4.15:
  <<: *base
  user: deploy
  stage: development
  roles: app
  deploy_path: ~/bot